### ISSUE TITLE
Only a white screen when not online

### ISSUE THREAD

**Issue by probonopd** [coranos/elastos-light-wallet#1]
Only a white screen when not online

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/c9a2fc851098da6aea13ebeffce00c826bd56a87/database/elastos-light-wallet/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1245

**Comment by coranos** [comment]
Please retest with RC5.

**Comment by probonopd** [comment]
Thank you, it is working 👍
