### ISSUE TITLE
"Balance Received:Success 0 " when sending a tx

### ISSUE THREAD

**Issue by talhaidris7** [coranos/elastos-light-wallet#7]
![Screenshot 2019-11-19 at 15 46 39](https://user-images.githubusercontent.com/38874006/69151697-cc51fa80-0ae3-11ea-911d-8b271218d07e.png)

Not sure whats the point or meaning of "Balance Received:Success 0 " when sending a transaction

**Comment by coranos** [comment]
it just means there was no error getting balance from the blockchain.
if the blockchain is down, an error will be displayed.
